VERSION: str

class WarMACError(Exception):
    def __init__(self, message: str = ...) -> None: ...

class SubcommandError(WarMACError):
    def __init__(self) -> None: ...

class InternalServerError(WarMACError):
    def __init__(self) -> None: ...

class MethodNotAllowedError(WarMACError):
    def __init__(self) -> None: ...

class MalformedURLError(WarMACError):
    def __init__(self) -> None: ...

class ForbiddenRequestError(WarMACError):
    def __init__(self) -> None: ...

class UnauthorizedAccessError(WarMACError):
    def __init__(self) -> None: ...

class UnknownError(WarMACError):
    def __init__(self, status_code: int) -> None: ...
