repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.18.1"
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "v0.24.1"
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/PyCQA/docformatter
    rev: "v1.7.7"
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [-i, -e ./tests]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.4"
    hooks:
      - id: ruff-check
        args: [--exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.0"
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies:
          [msgspec==0.19.0, urllib3==2.4.0, pytest==8.3.5, pytest-mock==3.14.1]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
