[build-system]
    build-backend = "poetry.core.masonry.api"
    requires      = ["poetry-core"]

[project]
    authors = [{name = "Noah Jenner", email = "noah.jenner@proton.me"}]
    classifiers = [
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
    ]
    description = "Warframe Market Average Calculator"
    name = "WarMAC_Eutropios"
    readme = "README.md"
    requires-python = ">=3.9"
    version = "0.0.1"

[project.urls]
    "Bug Tracker" = "https://github.com/Eutropios/WarMAC/issues"
    "Homepage"    = "https://github.com/Eutropios/WarMAC"

[tool.poetry]
    authors     = ["Noah Jenner <noah.jenner@proton.me>"]
    description = ""
    name        = "warmac"
    readme      = "README.md"
    version     = "0.1.0"

[tool.poetry.dependencies]
    python = "^3.11"

[tool.mypy]
    python_version = "3.9"

[[tool.mypy.overrides]]
    module = "_arguments.py"

[tool.ruff]
    ignore = ["ANN101", "UP007"]
    line-length = 88
    select = [
        "A",
        "ANN",
        "ARG",
        "B",
        "BLE",
        "C4",
        "C90",
        "D",
        "DTZ",
        "E",
        "EM",
        "ERA",
        "EXE",
        "F",
        "FBT",
        "INP",
        "INT",
        "N",
        "PIE",
        "PL",
        "PYI",
        "Q",
        "RET",
        "RSE",
        "RUF",
        "S110",
        "S112",
        "SIM",
        "TID",
        "TRY",
        "UP",
        "W",
    ]

[tool.ruff.pydocstyle]
    convention = "pep257"

[tool.black]
    exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
    include = '\.pyi?$'
    line-length = 88
    verbose = true
