name: Lint Docs

on:
  push:
    paths:
      - "docs/source/**"
  pull_request:
    paths:
      - "docs/source/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          version: "0.9.26"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --no-dev --group docs

      - name: Run sphinx-lint
        run: uv run sphinx-lint --max-line-length 80 docs
