name: Validate Project Files
# Lint and format config files, readme, etc

on:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"
      - ".github/**"
      - "README.md"
  pull_request:
    paths:
      - "pyproject.toml"
      - ".github/**"
      - "README.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: setup-tombi
        uses: tombi-toml/setup-tombi@df58d64dbb5163ba3413f0b75b4251e3fb5d250d # v1.2.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: "latest"

      - name: Validate TOML files
        run: tombi lint pyproject.toml

      - name: Format TOML files
        run: tombi format --check --diff pyproject.toml

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24.1.0
        with:
          config: ".markdownlint.yaml"
          globs: "**/*.md"
