name: Test

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "docs/conf.py"
      - "tests/**"
  pull_request:
    paths:
      - "src/**"
      - "docs/conf.py"
      - "tests/**"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.14t"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "0.9.26"
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: uv sync --no-dev --locked --group test
      - name: Run tests
        run: uv run -m pytest tests -vv
