name: Test

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "docs/source/conf.py"
      - "tests/**"
  pull_request:
    paths:
      - "src/**"
      - "docs/source/conf.py"
      - "tests/**"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.14t"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: "0.9.26"
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: uv sync --no-dev --locked --group test
      - name: Run tests
        run: uv run -m pytest tests -vv
